# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

from connections import Connection
from payment import Ui_Payment


class Login_Form(QMainWindow):
    def __init__(self, Payment, connection):
        super().__init__()
        self.payment_ui = Payment
        self.setObjectName("Form")
        self.resize(440, 540)
        self.setStyleSheet("background-color: #60a3bc")
        self.message_box = QtWidgets.QMessageBox()
        self.api = connection
        self.login_box = QtWidgets.QFrame(self)
        self.login_box.setGeometry(QtCore.QRect(20, 140, 400, 380))
        self.login_box.setAutoFillBackground(False)
        self.login_box.setStyleSheet("  background: #f39c12;\n"
                                     "  border-radius: 5px;")
        self.login_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_box.setObjectName("login_box")
        self.brand_logo = QtWidgets.QFrame(self.login_box)
        self.brand_logo.setGeometry(QtCore.QRect(120, -80, 170, 170))
        self.brand_logo.setStyleSheet("border-radius: 85px;\n"
                                      "background: #60a3bc;")
        self.brand_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.brand_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.brand_logo.setObjectName("brand_logo")
        self.login = QtWidgets.QLineEdit(self.login_box)
        self.login.setGeometry(QtCore.QRect(120, 120, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.login.setFont(font)
        self.login.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "border-bottom-left-radius: 0;\n"
                                 "border-top-left-radius: 0;")
        self.login.setText("")
        self.login.setObjectName("login")
        self.user_icon = QtWidgets.QLabel(self.login_box)
        self.user_icon.setGeometry(QtCore.QRect(60, 120, 60, 51))
        self.user_icon.setStyleSheet("background-color: rgb(204, 0, 0);\n"
                                     "border-top-right-radius: 0;\n"
                                     "border-bottom-right-radius: 0;")
        self.user_icon.setText("")
        self.user_icon.setObjectName("user_icon")
        self.key_icon = QtWidgets.QLabel(self.login_box)
        self.key_icon.setGeometry(QtCore.QRect(60, 210, 60, 51))
        self.key_icon.setStyleSheet("background-color: rgb(204, 0, 0);\n"
                                    "border-top-right-radius: 0;\n"
                                    "border-bottom-right-radius: 0;")
        self.key_icon.setText("")
        self.key_icon.setObjectName("key_icon")
        self.password = QtWidgets.QLineEdit(self.login_box)
        self.password.setGeometry(QtCore.QRect(120, 210, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-bottom-left-radius: 0;\n"
                                    "border-top-left-radius: 0;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.pushButton = QtWidgets.QPushButton(self.login_box)
        self.pushButton.setGeometry(QtCore.QRect(70, 294, 280, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setStyleSheet("QPushButton {background-color: rgb(204, 0, 0);\n"
                                      "color: #ffffff;\n"
                                      "}\n"
                                      "QPushButton:hover {background-color: rgb(190, 0, 0);\n"
                                      "color: #ffffff;\n"
                                      "}\n"
                                      "QPushButton:pressed {background-color: rgb(150, 0, 0);\n"
                                      "color: #ffffff;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.graphicsView = QtWidgets.QGraphicsView(self)
        self.graphicsView.setGeometry(QtCore.QRect(150, 70, 150, 150))
        self.graphicsView.setStyleSheet("background-color: rgb(204, 0, 0);\n"
                                        "border-radius: 75px;")
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Kirish"))
        self.pushButton.clicked.connect(self.on_submit)

    def on_submit(self):
        if self.login.text() == '':
            self.message_box.setText("Iltimos loginingizni kiriting!")
            self.message_box.exec_()
        elif self.password.text() == '':
            self.message_box.setText("Iltimos parolingizni kiriting!")
            self.message_box.exec_()
        else:
            response = self.api.checkUser(self.login.text(), self.password.text())
            if response.status_code == 200:
                self.hide()
                self.payment_ui.setupUi(self.api)
                self.payment_ui.show()
            else:
                self.message_box.setText(response._content)
                self.message_box.exec_()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    # Form = QtWidgets.QMainWindow()
    connection = Connection()
    payment = Ui_Payment()
    ui = Login_Form(payment, connection)
    ui.show()
    sys.exit(app.exec_())
